### ISSUE TITLE
Aspen sprint

### ISSUE THREAD

**Issue by msimet** [msimet/Stile#102]
I would like to address some of the outstanding issues in this repo over the next 2 weeks, while I'm in Aspen. This is mostly a checklist for me, but I'm happy to hear feedback on priorities etc if anyone has thoughts.

Plan to do:
- [x] Merge #81 and update existing branches
- [x] #103 unit test failures
- [x] Address any outstanding comments on #73 
- [ ] #101 add TravisCI and codecov -- this should streamline the rest of the work in this list.
- [x] #83 Allow plotting kwargs to the whisker & scatter plot tests
- [x] #78 update dependencies in the readme
- [x] #98 underscore bug in plotting routines
- [x] #85 fix usage of randoms in CorrFuncSysTests
- [x] #49 ability to plot requirements curves
- [x] #96 binned whisker plots
- [x] #94 hist2d option for scatterplots
- [ ] #89 Make sure we work with the latest version of the LSST pipeline, and probably refactor some of that code which is extremely messy at the moment. Also do #42, #48, #66, #70 and #80 within this update, probably, to the extent that they are not already done. (Note that we did #66 manually in the scripts we used for the Y1 paper--this issue adds those cuts within the LSST pipeline adapters.)

Everything up to issue #49 is pretty trivial bugfixing; #49, #96, and #94 should also be straightforward. #89 is a beast, though.  Actually a question there (which I may ask some of you in person): are we likely to want to interface with the DM stack for the next HSC analyses? If not, I may punt the whole set of issues until later.

May do, time allowing:
- [x] #97 parallelization - this is a pretty urgent task for getting Stile used by other people, but it's also going to be a big job, so I'll do what I can.
- [ ] #64 investigate numpy.rec.fromarrays
- [ ] #82 binning interface update
- [ ] #84 example scripts
- [ ] #61 default parameters from correlation functions
